#include "m1/numeric/trunc.hpp"
#include "catch.hpp"

TEST_CASE("Test m1::trunc", "[m1][m1::numeric]")
{
    using m1::trunc;

    CHECK(trunc(-6.8f) == Approx(-6.0f));
    CHECK(trunc(-6.5f) == Approx(-6.0f));
    CHECK(trunc(-6.2f) == Approx(-6.0f));
    CHECK(trunc(-6.0f) == Approx(-6.0f));
    CHECK(trunc(-5.8f) == Approx(-5.0f));
    CHECK(trunc(-5.5f) == Approx(-5.0f));
    CHECK(trunc(-5.2f) == Approx(-5.0f));
    CHECK(trunc(-5.0f) == Approx(-5.0f));
    CHECK(trunc(-4.8f) == Approx(-4.0f));
    CHECK(trunc(-4.5f) == Approx(-4.0f));
    CHECK(trunc(-4.2f) == Approx(-4.0f));
    CHECK(trunc(-4.0f) == Approx(-4.0f));
    CHECK(trunc(-3.8f) == Approx(-3.0f));
    CHECK(trunc(-3.5f) == Approx(-3.0f));
    CHECK(trunc(-3.2f) == Approx(-3.0f));
    CHECK(trunc(-3.0f) == Approx(-3.0f));
    CHECK(trunc(-2.8f) == Approx(-2.0f));
    CHECK(trunc(-2.5f) == Approx(-2.0f));
    CHECK(trunc(-2.2f) == Approx(-2.0f));
    CHECK(trunc(-2.0f) == Approx(-2.0f));
    CHECK(trunc(-1.8f) == Approx(-1.0f));
    CHECK(trunc(-1.5f) == Approx(-1.0f));
    CHECK(trunc(-1.2f) == Approx(-1.0f));
    CHECK(trunc(-1.0f) == Approx(-1.0f));
    CHECK(trunc(-0.8f) == Approx( 0.0f));
    CHECK(trunc(-0.5f) == Approx( 0.0f));
    CHECK(trunc(-0.2f) == Approx( 0.0f));
    CHECK(trunc( 0.0f) == Approx( 0.0f));
    CHECK(trunc(+0.2f) == Approx( 0.0f));
    CHECK(trunc(+0.5f) == Approx( 0.0f));
    CHECK(trunc(+0.8f) == Approx( 0.0f));
    CHECK(trunc(+1.0f) == Approx(+1.0f));
    CHECK(trunc(+1.2f) == Approx(+1.0f));
    CHECK(trunc(+1.5f) == Approx(+1.0f));
    CHECK(trunc(+1.8f) == Approx(+1.0f));
    CHECK(trunc(+2.0f) == Approx(+2.0f));
    CHECK(trunc(+2.2f) == Approx(+2.0f));
    CHECK(trunc(+2.5f) == Approx(+2.0f));
    CHECK(trunc(+2.8f) == Approx(+2.0f));
    CHECK(trunc(+3.0f) == Approx(+3.0f));
    CHECK(trunc(+3.2f) == Approx(+3.0f));
    CHECK(trunc(+3.5f) == Approx(+3.0f));
    CHECK(trunc(+3.8f) == Approx(+3.0f));
    CHECK(trunc(+4.0f) == Approx(+4.0f));
    CHECK(trunc(+4.2f) == Approx(+4.0f));
    CHECK(trunc(+4.5f) == Approx(+4.0f));
    CHECK(trunc(+4.8f) == Approx(+4.0f));
    CHECK(trunc(+5.0f) == Approx(+5.0f));
    CHECK(trunc(+5.2f) == Approx(+5.0f));
    CHECK(trunc(+5.5f) == Approx(+5.0f));
    CHECK(trunc(+5.8f) == Approx(+5.0f));
    CHECK(trunc(+6.0f) == Approx(+6.0f));
    CHECK(trunc(+6.2f) == Approx(+6.0f));
    CHECK(trunc(+6.5f) == Approx(+6.0f));
    CHECK(trunc(+6.8f) == Approx(+6.0f));

    CHECK(trunc(-6.8) == Approx(-6.0));
    CHECK(trunc(-6.5) == Approx(-6.0));
    CHECK(trunc(-6.2) == Approx(-6.0));
    CHECK(trunc(-6.0) == Approx(-6.0));
    CHECK(trunc(-5.8) == Approx(-5.0));
    CHECK(trunc(-5.5) == Approx(-5.0));
    CHECK(trunc(-5.2) == Approx(-5.0));
    CHECK(trunc(-5.0) == Approx(-5.0));
    CHECK(trunc(-4.8) == Approx(-4.0));
    CHECK(trunc(-4.5) == Approx(-4.0));
    CHECK(trunc(-4.2) == Approx(-4.0));
    CHECK(trunc(-4.0) == Approx(-4.0));
    CHECK(trunc(-3.8) == Approx(-3.0));
    CHECK(trunc(-3.5) == Approx(-3.0));
    CHECK(trunc(-3.2) == Approx(-3.0));
    CHECK(trunc(-3.0) == Approx(-3.0));
    CHECK(trunc(-2.8) == Approx(-2.0));
    CHECK(trunc(-2.5) == Approx(-2.0));
    CHECK(trunc(-2.2) == Approx(-2.0));
    CHECK(trunc(-2.0) == Approx(-2.0));
    CHECK(trunc(-1.8) == Approx(-1.0));
    CHECK(trunc(-1.5) == Approx(-1.0));
    CHECK(trunc(-1.2) == Approx(-1.0));
    CHECK(trunc(-1.0) == Approx(-1.0));
    CHECK(trunc(-0.8) == Approx( 0.0));
    CHECK(trunc(-0.5) == Approx( 0.0));
    CHECK(trunc(-0.2) == Approx( 0.0));
    CHECK(trunc( 0.0) == Approx( 0.0));
    CHECK(trunc(+0.2) == Approx( 0.0));
    CHECK(trunc(+0.5) == Approx( 0.0));
    CHECK(trunc(+0.8) == Approx( 0.0));
    CHECK(trunc(+1.0) == Approx(+1.0));
    CHECK(trunc(+1.2) == Approx(+1.0));
    CHECK(trunc(+1.5) == Approx(+1.0));
    CHECK(trunc(+1.8) == Approx(+1.0));
    CHECK(trunc(+2.0) == Approx(+2.0));
    CHECK(trunc(+2.2) == Approx(+2.0));
    CHECK(trunc(+2.5) == Approx(+2.0));
    CHECK(trunc(+2.8) == Approx(+2.0));
    CHECK(trunc(+3.0) == Approx(+3.0));
    CHECK(trunc(+3.2) == Approx(+3.0));
    CHECK(trunc(+3.5) == Approx(+3.0));
    CHECK(trunc(+3.8) == Approx(+3.0));
    CHECK(trunc(+4.0) == Approx(+4.0));
    CHECK(trunc(+4.2) == Approx(+4.0));
    CHECK(trunc(+4.5) == Approx(+4.0));
    CHECK(trunc(+4.8) == Approx(+4.0));
    CHECK(trunc(+5.0) == Approx(+5.0));
    CHECK(trunc(+5.2) == Approx(+5.0));
    CHECK(trunc(+5.5) == Approx(+5.0));
    CHECK(trunc(+5.8) == Approx(+5.0));
    CHECK(trunc(+6.0) == Approx(+6.0));
    CHECK(trunc(+6.2) == Approx(+6.0));
    CHECK(trunc(+6.5) == Approx(+6.0));
    CHECK(trunc(+6.8) == Approx(+6.0));
}
