# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mike\Code\BlackBox\tools\FlowSystemDesigner\Ui_FlowSystemDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlowSystemDesigner(object):
    def setupUi(self, FlowSystemDesigner):
        FlowSystemDesigner.setObjectName(_fromUtf8("FlowSystemDesigner"))
        FlowSystemDesigner.resize(1024, 768)
        self.flowSystemDesignerContents = QtGui.QWidget(FlowSystemDesigner)
        self.flowSystemDesignerContents.setObjectName(_fromUtf8("flowSystemDesignerContents"))
        self.gridLayout = QtGui.QGridLayout(self.flowSystemDesignerContents)
        self.gridLayout.setMargin(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.systemDesignerArea = QtGui.QScrollArea(self.flowSystemDesignerContents)
        self.systemDesignerArea.setWidgetResizable(True)
        self.systemDesignerArea.setObjectName(_fromUtf8("systemDesignerArea"))
        self.systemDesignerAreaContents = QtGui.QWidget()
        self.systemDesignerAreaContents.setGeometry(QtCore.QRect(0, 0, 758, 723))
        self.systemDesignerAreaContents.setObjectName(_fromUtf8("systemDesignerAreaContents"))
        self.systemDesignerArea.setWidget(self.systemDesignerAreaContents)
        self.gridLayout.addWidget(self.systemDesignerArea, 0, 0, 1, 1)
        FlowSystemDesigner.setCentralWidget(self.flowSystemDesignerContents)
        self.menubar = QtGui.QMenuBar(FlowSystemDesigner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setEnabled(False)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        FlowSystemDesigner.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FlowSystemDesigner)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        FlowSystemDesigner.setStatusBar(self.statusbar)
        self.componentDefinitionListDock = QtGui.QDockWidget(FlowSystemDesigner)
        self.componentDefinitionListDock.setObjectName(_fromUtf8("componentDefinitionListDock"))
        self.componentDefinitionListDockContents = QtGui.QWidget()
        self.componentDefinitionListDockContents.setObjectName(_fromUtf8("componentDefinitionListDockContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.componentDefinitionListDockContents)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.componentDefinitionList = QtGui.QListWidget(self.componentDefinitionListDockContents)
        self.componentDefinitionList.setObjectName(_fromUtf8("componentDefinitionList"))
        self.gridLayout_3.addWidget(self.componentDefinitionList, 0, 1, 1, 1)
        self.componentDefinitionListDock.setWidget(self.componentDefinitionListDockContents)
        FlowSystemDesigner.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.componentDefinitionListDock)
        self.componentActiveDefinitionDock = QtGui.QDockWidget(FlowSystemDesigner)
        self.componentActiveDefinitionDock.setObjectName(_fromUtf8("componentActiveDefinitionDock"))
        self.componentActiveDefinitionDockContents = QtGui.QWidget()
        self.componentActiveDefinitionDockContents.setObjectName(_fromUtf8("componentActiveDefinitionDockContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.componentActiveDefinitionDockContents)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.componentDefinitionEditor = FlowComponentDefinitionEditor(self.componentActiveDefinitionDockContents)
        self.componentDefinitionEditor.setObjectName(_fromUtf8("componentDefinitionEditor"))
        self.gridLayout_4.addWidget(self.componentDefinitionEditor, 0, 0, 1, 1)
        self.componentActiveDefinitionDock.setWidget(self.componentActiveDefinitionDockContents)
        FlowSystemDesigner.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.componentActiveDefinitionDock)
        self.actionFileOpen = QtGui.QAction(FlowSystemDesigner)
        self.actionFileOpen.setObjectName(_fromUtf8("actionFileOpen"))
        self.actionFileSave = QtGui.QAction(FlowSystemDesigner)
        self.actionFileSave.setObjectName(_fromUtf8("actionFileSave"))
        self.actionFileSaveAs = QtGui.QAction(FlowSystemDesigner)
        self.actionFileSaveAs.setObjectName(_fromUtf8("actionFileSaveAs"))
        self.actionFileExit = QtGui.QAction(FlowSystemDesigner)
        self.actionFileExit.setObjectName(_fromUtf8("actionFileExit"))
        self.actionHelpAbout = QtGui.QAction(FlowSystemDesigner)
        self.actionHelpAbout.setObjectName(_fromUtf8("actionHelpAbout"))
        self.actionViewComponentDefinitionList = QtGui.QAction(FlowSystemDesigner)
        self.actionViewComponentDefinitionList.setCheckable(True)
        self.actionViewComponentDefinitionList.setObjectName(_fromUtf8("actionViewComponentDefinitionList"))
        self.actionViewComponentActiveDefinition = QtGui.QAction(FlowSystemDesigner)
        self.actionViewComponentActiveDefinition.setCheckable(True)
        self.actionViewComponentActiveDefinition.setObjectName(_fromUtf8("actionViewComponentActiveDefinition"))
        self.actionFileNew = QtGui.QAction(FlowSystemDesigner)
        self.actionFileNew.setObjectName(_fromUtf8("actionFileNew"))
        self.actionProjectAddComponentDefinition = QtGui.QAction(FlowSystemDesigner)
        self.actionProjectAddComponentDefinition.setObjectName(_fromUtf8("actionProjectAddComponentDefinition"))
        self.actionUndo = QtGui.QAction(FlowSystemDesigner)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(FlowSystemDesigner)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCut = QtGui.QAction(FlowSystemDesigner)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(FlowSystemDesigner)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(FlowSystemDesigner)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.menuFile.addAction(self.actionFileNew)
        self.menuFile.addAction(self.actionFileOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileSave)
        self.menuFile.addAction(self.actionFileSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileExit)
        self.menuView.addAction(self.actionViewComponentDefinitionList)
        self.menuView.addAction(self.actionViewComponentActiveDefinition)
        self.menuHelp.addAction(self.actionHelpAbout)
        self.menuProject.addAction(self.actionProjectAddComponentDefinition)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(FlowSystemDesigner)
        QtCore.QObject.connect(self.actionFileExit, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.close)
        QtCore.QObject.connect(self.actionHelpAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.helpAbout)
        QtCore.QObject.connect(self.actionFileNew, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.newProject)
        QtCore.QObject.connect(self.actionFileOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.openProject)
        QtCore.QObject.connect(self.actionFileSave, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.saveProject)
        QtCore.QObject.connect(self.actionFileSaveAs, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.saveProjectAs)
        QtCore.QObject.connect(self.actionViewComponentDefinitionList, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.componentDefinitionListDock.setVisible)
        QtCore.QObject.connect(self.actionViewComponentActiveDefinition, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.componentActiveDefinitionDock.setVisible)
        QtCore.QObject.connect(self.componentDefinitionListDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionViewComponentDefinitionList.setChecked)
        QtCore.QObject.connect(self.componentActiveDefinitionDock, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionViewComponentActiveDefinition.setChecked)
        QtCore.QObject.connect(self.actionProjectAddComponentDefinition, QtCore.SIGNAL(_fromUtf8("triggered()")), FlowSystemDesigner.addComponentDefinition)
        QtCore.QObject.connect(self.componentDefinitionList, QtCore.SIGNAL(_fromUtf8("currentTextChanged(QString)")), FlowSystemDesigner.showComponentDefinition)
        QtCore.QObject.connect(FlowSystemDesigner, QtCore.SIGNAL(_fromUtf8("activeProjectChanged()")), FlowSystemDesigner.refreshProject)
        QtCore.QMetaObject.connectSlotsByName(FlowSystemDesigner)

    def retranslateUi(self, FlowSystemDesigner):
        FlowSystemDesigner.setWindowTitle(_translate("FlowSystemDesigner", "Flow System Designer", None))
        self.menuFile.setTitle(_translate("FlowSystemDesigner", "File", None))
        self.menuView.setTitle(_translate("FlowSystemDesigner", "View", None))
        self.menuHelp.setTitle(_translate("FlowSystemDesigner", "Help", None))
        self.menuProject.setTitle(_translate("FlowSystemDesigner", "Project", None))
        self.menuEdit.setTitle(_translate("FlowSystemDesigner", "Edit", None))
        self.componentDefinitionListDock.setWindowTitle(_translate("FlowSystemDesigner", "Component Definition List", None))
        self.componentActiveDefinitionDock.setWindowTitle(_translate("FlowSystemDesigner", "Component Definition", None))
        self.actionFileOpen.setText(_translate("FlowSystemDesigner", "Open...", None))
        self.actionFileOpen.setShortcut(_translate("FlowSystemDesigner", "Ctrl+O", None))
        self.actionFileSave.setText(_translate("FlowSystemDesigner", "Save", None))
        self.actionFileSave.setShortcut(_translate("FlowSystemDesigner", "Ctrl+S", None))
        self.actionFileSaveAs.setText(_translate("FlowSystemDesigner", "Save As", None))
        self.actionFileExit.setText(_translate("FlowSystemDesigner", "Exit", None))
        self.actionHelpAbout.setText(_translate("FlowSystemDesigner", "About", None))
        self.actionViewComponentDefinitionList.setText(_translate("FlowSystemDesigner", "Component Definition List", None))
        self.actionViewComponentActiveDefinition.setText(_translate("FlowSystemDesigner", "Component Definition", None))
        self.actionFileNew.setText(_translate("FlowSystemDesigner", "New", None))
        self.actionFileNew.setShortcut(_translate("FlowSystemDesigner", "Ctrl+N", None))
        self.actionProjectAddComponentDefinition.setText(_translate("FlowSystemDesigner", "Add Component Definition...", None))
        self.actionUndo.setText(_translate("FlowSystemDesigner", "Undo", None))
        self.actionUndo.setShortcut(_translate("FlowSystemDesigner", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("FlowSystemDesigner", "Redo", None))
        self.actionRedo.setShortcut(_translate("FlowSystemDesigner", "Ctrl+Y", None))
        self.actionCut.setText(_translate("FlowSystemDesigner", "Cut", None))
        self.actionCut.setShortcut(_translate("FlowSystemDesigner", "Ctrl+X", None))
        self.actionCopy.setText(_translate("FlowSystemDesigner", "Copy", None))
        self.actionCopy.setShortcut(_translate("FlowSystemDesigner", "Ctrl+C", None))
        self.actionPaste.setText(_translate("FlowSystemDesigner", "Paste", None))
        self.actionPaste.setShortcut(_translate("FlowSystemDesigner", "Ctrl+V", None))

from FlowComponentDefinitionEditor import FlowComponentDefinitionEditor
